STRAVA_CLIENT_ID= "95885"
STRAVA_CLIENT_SECRET= "9bd58f9a50e4a12d165a373bec9afe40754f4962"
SUPABASE_URL= "https://iaxuhfmtvzhwzytjyjpm.supabase.co"
SUPABASE_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlheHVoZm10dnpod3p5dGp5anBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMDI1MjcsImV4cCI6MjA1Njc3ODUyN30.XVx3o9WlxF74Nhe9393TYGbiagQz5RymNthCs2EfZ3Q"
REDIRECT_URI= "100milles.streamlit.app"